// apps/platform/components/account-profile.tsx
"use client"

import { useEffect, useRef, useState, type FormEvent } from "react"
import { Camera, Check, LogOut, RefreshCw, ShieldCheck } from "lucide-react"
import {
  avatarCropRegion,
  cropAvatarUpload,
  type AvatarCrop,
} from "@vetoexpress/auth/avatar"
import {
  AuthError,
  type PlatformUser,
  updateAccountProfile,
  refreshAccountProfile,
  sendAccountPasswordCode,
  resetAccountPassword,
} from "@/lib/auth-client"
import { Button } from "@/components/ui/button"
import { Input } from "@/components/ui/input"
import { Label } from "@/components/ui/label"
import { Badge } from "@/components/ui/badge"
import {
  Card,
  CardHeader,
  CardTitle,
  CardDescription,
  CardContent,
  CardFooter,
} from "@/components/ui/card"
import {
  Dialog,
  DialogContent,
  DialogHeader,
  DialogTitle,
  DialogDescription,
  DialogFooter,
} from "@/components/ui/dialog"
import { UserAvatar } from "@/components/user-avatar"

export function AccountProfile({
  user,
  token,
  onSignOut,
}: {
  user: PlatformUser
  token: string
  onSignOut: () => void
}) {
  const [name, setName] = useState(user.name)
  const [avatar, setAvatar] = useState(user.avatar)
  const [avatarData, setAvatarData] = useState<string>()
  const [source, setSource] = useState("")
  const [crop, setCrop] = useState<AvatarCrop>({ zoom: 1, x: 0, y: 0 })
  const [code, setCode] = useState("")
  const [password, setPassword] = useState("")
  const [confirmation, setConfirmation] = useState("")
  const [busy, setBusy] = useState(false)
  const [error, setError] = useState("")
  const [notice, setNotice] = useState("")
  const [deadline, setDeadline] = useState(0)
  const [cooldown, setCooldown] = useState(0)
  const file = useRef<HTMLInputElement>(null)
  const canvas = useRef<HTMLCanvasElement>(null)
  const drag = useRef<{ x: number; y: number; crop: AvatarCrop } | null>(null)

  useEffect(() => {
    setName(user.name)
  }, [user.name])
  useEffect(() => {
    setAvatar(user.avatar)
    setAvatarData(undefined)
  }, [user.avatar])
  useEffect(
    () => () => {
      if (source) URL.revokeObjectURL(source)
    },
    [source]
  )
  useEffect(() => {
    if (!deadline) return
    const tick = () =>
      setCooldown(Math.max(0, Math.ceil((deadline - Date.now()) / 1000)))
    tick()
    const timer = setInterval(tick, 1000)
    return () => clearInterval(timer)
  }, [deadline])
  useEffect(() => {
    if (!source) return
    let cancelled = false
    const image = new Image()
    image.src = source
    void image
      .decode()
      .then(() => {
        if (cancelled) return
        const context = canvas.current?.getContext("2d")
        if (!context) return
        const region = avatarCropRegion(
          image.naturalWidth,
          image.naturalHeight,
          crop
        )
        context.clearRect(0, 0, 256, 256)
        context.drawImage(
          image,
          region.x,
          region.y,
          region.size,
          region.size,
          0,
          0,
          256,
          256
        )
      })
      .catch(() => {
        if (!cancelled) {
          setError("无法读取图片，请重新选择。")
          setSource("")
        }
      })
    return () => {
      cancelled = true
    }
  }, [source, crop])

  async function run(operation: () => Promise<void>) {
    if (busy) return
    setBusy(true)
    setError("")
    setNotice("")
    try {
      await operation()
    } catch (caught) {
      if (caught instanceof AuthError && caught.status === 401) onSignOut()
      else
        setError(caught instanceof Error ? caught.message : "操作失败，请重试")
    } finally {
      setBusy(false)
    }
  }
  function save(event: FormEvent) {
    event.preventDefault()
    if (!name.trim()) {
      setError("请填写用户名")
      return
    }
    if (name.trim() === user.name && !avatarData) {
      setNotice("没有需要保存的更改")
      return
    }
    void run(async () => {
      const updated = await updateAccountProfile(token, {
        name: name.trim(),
        ...(avatarData ? { avatar: avatarData } : {}),
      })
      setName(updated.name)
      setAvatar(updated.avatar)
      setAvatarData(undefined)
      setNotice("个人信息已更新")
    })
  }
  function reset(event: FormEvent) {
    event.preventDefault()
    if (password.length < 6 || password.length > 1024) {
      setError("密码应为 6–1024 个字符")
      return
    }
    if (password !== confirmation) {
      setError("两次输入的密码不一致")
      return
    }
    if (!/^\d{6}$/.test(code.trim())) {
      setError("请输入邮箱收到的 6 位验证码")
      return
    }
    void run(async () => {
      await resetAccountPassword(user.email, code.trim(), password)
      setCode("")
      setPassword("")
      setConfirmation("")
      onSignOut()
    })
  }

  return (
    <div className="mx-auto flex w-full max-w-3xl flex-col gap-5">
      {error && (
        <p
          role="alert"
          className="rounded-lg border border-destructive/30 p-4 text-sm text-destructive"
        >
          {error}
        </p>
      )}
      {notice && (
        <p role="status" className="rounded-lg border p-4 text-sm">
          {notice}
        </p>
      )}
      <Card>
        <CardHeader>
          <div className="flex flex-wrap items-center gap-4">
            <input
              ref={file}
              id="platform-avatar-upload"
              type="file"
              accept="image/*"
              hidden
              disabled={busy}
              onChange={(event) => {
                const selected = event.target.files?.[0]
                event.target.value = ""
                if (!selected) return
                if (!selected.type.startsWith("image/")) {
                  setError("请选择支持的图片文件。")
                  return
                }
                setCrop({ zoom: 1, x: 0, y: 0 })
                setSource(URL.createObjectURL(selected))
              }}
            />
            <Button
              variant="ghost"
              className="group relative size-20 rounded-full p-0"
              aria-label="更换头像"
              disabled={busy}
              onClick={() => file.current?.click()}
            >
              <UserAvatar
                name={user.name}
                avatar={avatar || undefined}
                className="size-20 text-2xl"
              />
              <span className="absolute inset-0 flex items-center justify-center rounded-full bg-background/70 opacity-0 transition-opacity group-hover:opacity-100 group-focus-visible:opacity-100">
                <Camera />
              </span>
            </Button>
            <div className="flex min-w-0 flex-1 flex-col gap-2">
              <div className="flex flex-wrap items-center gap-2">
                <h2 className="text-xl font-semibold break-all">{user.name}</h2>
                <Badge variant="secondary">
                  <Check />
                  已登录
                </Badge>
              </div>
              <p className="text-sm break-all text-muted-foreground">
                {user.email}
              </p>
              <p className="text-xs text-muted-foreground">
                点击头像更换图片，裁剪后自动压缩 · 最大 512 KB
              </p>
            </div>
          </div>
        </CardHeader>
      </Card>
      <form onSubmit={save}>
        <Card>
          <CardHeader>
            <CardTitle role="heading" aria-level={2}>
              个人信息
            </CardTitle>
            <CardDescription>管理你的显示名称和账号资料。</CardDescription>
          </CardHeader>
          <CardContent className="flex flex-col gap-5">
            <div className="flex flex-col gap-2">
              <Label htmlFor="platform-name">用户名</Label>
              <Input
                id="platform-name"
                value={name}
                onChange={(event) => setName(event.target.value)}
                maxLength={200}
                disabled={busy}
              />
              <p className="text-xs text-muted-foreground">
                用于展示你的身份，最多 200 个字符。
              </p>
            </div>
            <div className="grid gap-5 sm:grid-cols-2">
              <div className="flex flex-col gap-2">
                <Label htmlFor="platform-email">邮箱</Label>
                <Input id="platform-email" value={user.email} readOnly />
                <p className="text-xs text-muted-foreground">
                  注册邮箱，暂不支持修改。
                </p>
              </div>
              <div className="flex flex-col gap-2">
                <Label htmlFor="platform-organization">所属模联</Label>
                <Input
                  id="platform-organization"
                  value={user.organization}
                  readOnly
                />
              </div>
            </div>
          </CardContent>
          <CardFooter className="flex-wrap justify-between gap-3">
            <p className="text-xs text-muted-foreground">
              {user.created_at
                ? `注册于 ${new Date(user.created_at).toLocaleDateString("zh-CN", { year: "numeric", month: "long", day: "numeric" })}`
                : "头像与用户名将在保存后更新。"}
            </p>
            <Button type="submit" disabled={busy}>
              保存修改
            </Button>
          </CardFooter>
        </Card>
      </form>
      <form onSubmit={reset}>
        <Card>
          <CardHeader>
            <CardTitle
              role="heading"
              aria-level={2}
              className="flex items-center gap-2"
            >
              <ShieldCheck />
              安全设置
            </CardTitle>
            <CardDescription>通过注册邮箱的验证码重置密码。</CardDescription>
          </CardHeader>
          <CardContent className="flex flex-col gap-5">
            <div className="flex flex-col gap-2">
              <Label htmlFor="platform-code">邮箱验证码</Label>
              <div className="flex gap-2">
                <Input
                  id="platform-code"
                  value={code}
                  onChange={(event) => setCode(event.target.value)}
                  inputMode="numeric"
                  autoComplete="one-time-code"
                  maxLength={6}
                  placeholder="6 位验证码"
                  disabled={busy}
                />
                <Button
                  type="button"
                  variant="outline"
                  disabled={busy || cooldown > 0}
                  onClick={() => {
                    void run(async () => {
                      await sendAccountPasswordCode(user.email)
                      setDeadline(Date.now() + 60000)
                      setNotice("验证码已发送到注册邮箱，5 分钟内有效")
                    })
                  }}
                >
                  {cooldown ? `${cooldown} 秒后重发` : "发送验证码"}
                </Button>
              </div>
              <p className="text-xs text-muted-foreground">
                验证码将发送至 {user.email}，5 分钟内有效。
              </p>
            </div>
            <div className="grid gap-5 sm:grid-cols-2">
              <div className="flex flex-col gap-2">
                <Label htmlFor="platform-password">新密码</Label>
                <Input
                  id="platform-password"
                  type="password"
                  autoComplete="new-password"
                  value={password}
                  onChange={(event) => setPassword(event.target.value)}
                  placeholder="至少 6 位字符"
                  disabled={busy}
                />
              </div>
              <div className="flex flex-col gap-2">
                <Label htmlFor="platform-confirmation">确认新密码</Label>
                <Input
                  id="platform-confirmation"
                  type="password"
                  autoComplete="new-password"
                  value={confirmation}
                  onChange={(event) => setConfirmation(event.target.value)}
                  disabled={busy}
                />
              </div>
            </div>
          </CardContent>
          <CardFooter className="flex-wrap justify-between gap-3">
            <p className="text-xs text-muted-foreground">
              重置后，所有设备需使用新密码重新登录。
            </p>
            <Button
              variant="outline"
              type="submit"
              disabled={busy || !password || !confirmation}
            >
              重置密码
            </Button>
          </CardFooter>
        </Card>
      </form>
      <Card>
        <CardHeader>
          <CardTitle role="heading" aria-level={2}>
            登录状态
          </CardTitle>
          <CardDescription>管理当前账号的登录状态。</CardDescription>
        </CardHeader>
        <CardFooter className="flex-wrap gap-2">
          <Button
            variant="outline"
            disabled={busy}
            onClick={() => {
              void run(async () => {
                const updated = await refreshAccountProfile(token)
                setName(updated.name)
                setAvatar(updated.avatar)
                setAvatarData(undefined)
                setNotice("账号信息已刷新")
              })
            }}
          >
            <RefreshCw />
            刷新账号信息
          </Button>
          <Button variant="destructive" disabled={busy} onClick={onSignOut}>
            <LogOut />
            退出登录
          </Button>
        </CardFooter>
      </Card>
      <Dialog
        open={!!source}
        onOpenChange={(open) => {
          if (!open && !busy) setSource("")
        }}
      >
        <DialogContent className="sm:max-w-md">
          <DialogHeader>
            <DialogTitle>裁剪头像</DialogTitle>
            <DialogDescription>
              拖动头像或调整位置和缩放，预览圆形头像。
            </DialogDescription>
          </DialogHeader>
          <canvas
            ref={canvas}
            width={256}
            height={256}
            className="mx-auto size-64 touch-none rounded-full bg-muted"
            aria-label="头像裁剪预览"
            onPointerDown={(event) => {
              event.currentTarget.setPointerCapture(event.pointerId)
              drag.current = { x: event.clientX, y: event.clientY, crop }
            }}
            onPointerMove={(event) => {
              const start = drag.current
              if (start && !busy)
                setCrop({
                  ...start.crop,
                  x: Math.max(
                    -1,
                    Math.min(1, start.crop.x - (event.clientX - start.x) / 128)
                  ),
                  y: Math.max(
                    -1,
                    Math.min(1, start.crop.y - (event.clientY - start.y) / 128)
                  ),
                })
            }}
            onPointerUp={() => {
              drag.current = null
            }}
            onPointerCancel={() => {
              drag.current = null
            }}
          />
          {(
            [
              ["zoom", "缩放", 1, 3],
              ["x", "水平位置", -1, 1],
              ["y", "垂直位置", -1, 1],
            ] as const
          ).map(([key, label, min, max]) => (
            <div key={key} className="flex flex-col gap-2">
              <Label htmlFor={`crop-${key}`}>{label}</Label>
              <input
                id={`crop-${key}`}
                type="range"
                min={min}
                max={max}
                step={0.01}
                value={crop[key]}
                disabled={busy}
                onChange={(event) =>
                  setCrop({ ...crop, [key]: Number(event.target.value) })
                }
              />
            </div>
          ))}
          <DialogFooter>
            <Button
              variant="outline"
              disabled={busy}
              onClick={() => setSource("")}
            >
              取消
            </Button>
            <Button
              disabled={busy}
              onClick={() => {
                void run(async () => {
                  const upload = await cropAvatarUpload(source, crop)
                  setAvatar(upload.dataUrl)
                  setAvatarData(upload.base64)
                  setSource("")
                })
              }}
            >
              裁剪
            </Button>
          </DialogFooter>
        </DialogContent>
      </Dialog>
    </div>
  )
}

// apps/frontend/src/lib/components/settings/pages/common/account-profile.svelte
<script lang="ts">
  import { User, Camera, LogOut, RefreshCw, Check, ShieldCheck, CircleCheck } from '@lucide/svelte'
  import type { AuthUser } from '@vetoexpress/auth'
  import { prepareAvatarUpload } from '@vetoexpress/auth/avatar'
  import * as Card from '$lib/components/ui/card'
  import { Badge } from '$lib/components/ui/badge'
  import { Button } from '$lib/components/ui/button'
  import { Input } from '$lib/components/ui/input'
  import { Spinner } from '$lib/components/ui/spinner'
  import * as Avatar from '$lib/components/ui/avatar'
  import * as ImageCropper from '$lib/components/ui/image-cropper'
  import * as Dialog from '$lib/components/ui/dialog'
  import * as Field from '$lib/components/ui/field'
  import * as Alert from '$lib/components/ui/alert'

  let {
    user,
    pending = false,
    onRefresh,
    onSignOut,
    onSave,
    onPassword,
    onSendPasswordCode
  }: {
    user: AuthUser
    pending?: boolean
    onRefresh: () => void
    onSignOut: () => void
    onSave?: (name: string, avatar?: string) => Promise<void>
    onPassword?: (code: string, password: string) => Promise<void>
    onSendPasswordCode?: () => Promise<void>
  } = $props()

  let editName = $state('')
  let avatarSrc = $state('')
  let avatarData = $state<string>()
  let newPassword = $state('')
  let confirmPassword = $state('')
  let passwordCode = $state('')
  let sendingCode = $state(false)
  let cooldownUntil = $state(0)
  let cooldown = $state(0)
  let saving = $state(false)
  let processingAvatar = $state(false)
  let error = $state('')
  let message = $state('')
  const savedName = $derived(user.name)
  const savedAvatar = $derived(user.avatar)
  const accountEmail = $derived(user.email)

  $effect(() => {
    const deadline = cooldownUntil
    if (!deadline) return
    cooldown = Math.max(0, Math.ceil((deadline - Date.now()) / 1000))
    const timer = setInterval(() => {
      cooldown = Math.max(0, Math.ceil((deadline - Date.now()) / 1000))
      if (!cooldown) clearInterval(timer)
    }, 1000)
    return () => clearInterval(timer)
  })

  async function sendPasswordCode() {
    if (!onSendPasswordCode || sendingCode || pending || cooldown) return
    sendingCode = true
    error = ''
    message = ''
    try {
      await onSendPasswordCode()
      cooldownUntil = Date.now() + 60_000
      message = '验证码已发送到注册邮箱，5 分钟内有效'
    } catch (caught) {
      error = caught instanceof Error ? caught.message : '验证码发送失败'
    } finally {
      sendingCode = false
    }
  }

  $effect(() => {
    accountEmail
    editName = savedName
  })
  $effect(() => {
    accountEmail
    avatarSrc = savedAvatar
    avatarData = undefined
  })

  async function cropped(src: string) {
    processingAvatar = true
    error = ''
    message = ''
    try {
      const upload = await prepareAvatarUpload(src)
      avatarSrc = upload.dataUrl
      avatarData = upload.base64
    } catch (caught) {
      avatarSrc = user.avatar
      avatarData = undefined
      error = caught instanceof Error ? caught.message : '无法读取头像'
    } finally {
      processingAvatar = false
      if (src.startsWith('blob:')) URL.revokeObjectURL(src)
    }
  }

  async function saveProfile(event: SubmitEvent) {
    event.preventDefault()
    if (saving || pending || processingAvatar) return
    error = ''
    message = ''
    if (!editName.trim()) {
      error = '请填写用户名'
      return
    }
    if (editName.trim() === user.name && !avatarData) {
      message = '没有需要保存的更改'
      return
    }
    if (!onSave) return
    saving = true
    try {
      await onSave(editName.trim(), avatarData)
      avatarData = undefined
      message = '个人信息已更新'
    } catch (caught) {
      error = caught instanceof Error ? caught.message : '保存失败'
    } finally {
      saving = false
    }
  }

  async function changePassword(event: SubmitEvent) {
    event.preventDefault()
    if (saving || pending) return
    error = ''
    message = ''
    if (newPassword.length < 6 || newPassword.length > 1024) {
      error = '密码应为 6–1024 个字符'
      return
    }
    if (newPassword !== confirmPassword) {
      error = '两次输入的密码不一致'
      return
    }
    if (!onPassword) return
    if (!/^\d{6}$/.test(passwordCode.trim())) {
      error = '请输入邮箱收到的 6 位验证码'
      return
    }
    saving = true
    try {
      await onPassword(passwordCode.trim(), newPassword)
      passwordCode = ''
      newPassword = ''
      confirmPassword = ''
      message = '密码已重置，请使用新密码重新登录'
    } catch (caught) {
      error = caught instanceof Error ? caught.message : '修改密码失败'
    } finally {
      saving = false
    }
  }
</script>

<div class="@container/profile flex flex-col gap-5">
  {#if error}
    <Alert.Root variant="destructive">
      <Alert.Title>操作失败</Alert.Title>
      <Alert.Description>{error}</Alert.Description>
    </Alert.Root>
  {/if}
  {#if message}
    <Alert.Root role="status">
      <CircleCheck />
      <Alert.Title>{message}</Alert.Title>
    </Alert.Root>
  {/if}

  <Card.Root>
    <Card.Header>
      <div class="flex flex-wrap items-center gap-4">
        <ImageCropper.Root
          id="account-avatar-upload"
          bind:src={avatarSrc}
          onCropped={cropped}
          onUnsupportedFile={() => (error = '请选择支持的图片文件。')}
          accept="image/*"
          disabled={!onSave || saving || pending}
        >
          <ImageCropper.Preview>
            {#snippet child({ src })}
              <Button
                variant="ghost"
                class="group relative size-20 rounded-full p-0"
                aria-label="更换头像"
                disabled={!onSave || saving || pending}
                onclick={() => document.getElementById('account-avatar-upload')?.click()}
              >
                <Avatar.Root class="size-20">
                  {#if src}<Avatar.Image {src} alt={user.name} />{/if}
                  <Avatar.Fallback><User /></Avatar.Fallback>
                </Avatar.Root>
                <span
                  class="absolute inset-0 flex items-center justify-center rounded-full bg-background/70 opacity-0 transition-opacity group-hover:opacity-100 group-focus-visible:opacity-100"
                >
                  <Camera />
                </span>
              </Button>
            {/snippet}
          </ImageCropper.Preview>
          <ImageCropper.Dialog>
            <Dialog.Title>裁剪头像</Dialog.Title>
            <Dialog.Description>拖动和缩放图片，裁剪为圆形头像。</Dialog.Description>
            <ImageCropper.Cropper cropShape="round" aspect={1} />
            <ImageCropper.Controls>
              <ImageCropper.Cancel /><ImageCropper.Crop />
            </ImageCropper.Controls>
          </ImageCropper.Dialog>
        </ImageCropper.Root>
        <div class="flex min-w-0 flex-1 flex-col gap-2">
          <div class="flex flex-wrap items-center gap-2">
            <h3 class="break-all text-xl font-semibold">{user.name}</h3>
            <Badge variant="secondary"><Check data-icon="inline-start" />已登录</Badge>
          </div>
          <p class="break-all text-sm text-muted-foreground">{user.email}</p>
          <p class="text-xs text-muted-foreground">
            点击头像更换图片，裁剪后自动压缩 · 最大 512 KB
          </p>
        </div>
      </div>
    </Card.Header>
  </Card.Root>

  <form id="account-profile-form" onsubmit={saveProfile}>
    <Card.Root>
      <Card.Header>
        <Card.Title role="heading" aria-level={3}>个人信息</Card.Title>
        <Card.Description>管理你的显示名称和账号资料。</Card.Description>
      </Card.Header>
      <Card.Content>
        <Field.FieldGroup class="gap-5">
          <Field.Field data-disabled={!onSave || saving || pending}>
            <Field.FieldLabel for="account-name">用户名</Field.FieldLabel>
            <Input
              id="account-name"
              bind:value={editName}
              maxlength={200}
              placeholder="输入用户名"
              disabled={!onSave || saving || pending}
            />
            <Field.FieldDescription>用于展示你的身份，最多 200 个字符。</Field.FieldDescription>
          </Field.Field>
          <Field.FieldGroup class="@min-[480px]/profile:flex-row">
            <Field.Field>
              <Field.FieldLabel for="account-profile-email">邮箱</Field.FieldLabel>
              <Input id="account-profile-email" value={user.email} readonly />
              <Field.FieldDescription>注册邮箱，暂不支持修改。</Field.FieldDescription>
            </Field.Field>
            <Field.Field>
              <Field.FieldLabel for="account-organization">所属模联</Field.FieldLabel>
              <Input id="account-organization" value={user.organization} readonly />
              <Field.FieldDescription>你的账号所属模联。</Field.FieldDescription>
            </Field.Field>
          </Field.FieldGroup>
        </Field.FieldGroup>
      </Card.Content>
      <Card.Footer class="flex-wrap justify-between gap-3 border-t pt-5">
        <p class="text-xs text-muted-foreground">
          {#if user.created_at}
            注册于 {new Date(user.created_at).toLocaleDateString('zh-CN', {
              year: 'numeric',
              month: 'long',
              day: 'numeric'
            })}
          {:else}
            头像与用户名将在保存后更新。
          {/if}
        </p>
        <Button type="submit" disabled={!onSave || saving || pending || processingAvatar}>
          {#if saving || processingAvatar}<Spinner data-icon="inline-start" />{/if}保存修改
        </Button>
      </Card.Footer>
    </Card.Root>
  </form>

  <form id="account-password-form" onsubmit={changePassword}>
    <Card.Root>
      <Card.Header>
        <Card.Title role="heading" aria-level={3}>安全设置</Card.Title>
        <Card.Description>通过注册邮箱的验证码重置密码。</Card.Description>
        <Card.Action><ShieldCheck class="size-5 text-muted-foreground" /></Card.Action>
      </Card.Header>
      <Card.Content>
        <Field.Field class="mb-5" data-disabled={!onPassword || saving || pending}>
          <Field.FieldLabel for="account-password-code">邮箱验证码</Field.FieldLabel>
          <div class="flex gap-2">
            <Input
              id="account-password-code"
              bind:value={passwordCode}
              inputmode="numeric"
              autocomplete="one-time-code"
              maxlength={6}
              placeholder="6 位验证码"
              disabled={!onPassword || saving || pending}
            />
            <Button
              type="button"
              variant="outline"
              disabled={!onSendPasswordCode || saving || sendingCode || pending || cooldown > 0}
              onclick={sendPasswordCode}
            >
              {sendingCode ? '发送中…' : cooldown ? `${cooldown} 秒后重发` : '发送验证码'}
            </Button>
          </div>
          <Field.FieldDescription>
            验证码将发送至 {user.email}，5 分钟内有效。
          </Field.FieldDescription>
        </Field.Field>
        <Field.FieldGroup class="@min-[480px]/profile:flex-row">
          <Field.Field data-disabled={!onPassword || saving || pending}>
            <Field.FieldLabel for="account-new-password">新密码</Field.FieldLabel>
            <Input
              id="account-new-password"
              type="password"
              autocomplete="new-password"
              bind:value={newPassword}
              placeholder="至少 6 位字符"
              disabled={!onPassword || saving || pending}
            />
          </Field.Field>
          <Field.Field data-disabled={!onPassword || saving || pending}>
            <Field.FieldLabel for="account-confirm-password">确认新密码</Field.FieldLabel>
            <Input
              id="account-confirm-password"
              type="password"
              autocomplete="new-password"
              bind:value={confirmPassword}
              placeholder="再次输入新密码"
              disabled={!onPassword || saving || pending}
            />
          </Field.Field>
        </Field.FieldGroup>
      </Card.Content>
      <Card.Footer class="flex-wrap justify-between gap-3 border-t pt-5">
        <p class="text-xs text-muted-foreground">重置后，所有设备需使用新密码重新登录。</p>
        <Button
          type="submit"
          variant="outline"
          disabled={!onPassword || saving || pending || !newPassword || !confirmPassword}
        >
          重置密码
        </Button>
      </Card.Footer>
    </Card.Root>
  </form>

  <Card.Root>
    <Card.Header>
      <Card.Title role="heading" aria-level={3}>登录状态</Card.Title>
      <Card.Description>退出后，本机 App 与内嵌云平台会同步退出。</Card.Description>
    </Card.Header>
    <Card.Footer class="flex-wrap gap-2">
      <Button variant="outline" disabled={saving || pending} onclick={onRefresh}>
        <RefreshCw data-icon="inline-start" />刷新账号信息
      </Button>
      <Button variant="destructive" disabled={saving || pending} onclick={onSignOut}>
        <LogOut data-icon="inline-start" />退出登录
      </Button>
    </Card.Footer>
  </Card.Root>
</div>
